# Generated by Django 3.0.3 on 2020-03-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200310_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'catParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Category Parent'),
        ),
    ]
