# Generated by Django 3.0.3 on 2020-03-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200314_1537'),
        ('product', '0008_auto_20200310_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpicture',
            name='PID',
        ),
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductPicture', verbose_name='Product Pictures'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='UID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='User ID'),
            preserve_default=False,
        ),
    ]
