# Generated by Django 3.0.3 on 2020-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200310_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_view',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Product  Image'),
        ),
    ]
