# Generated by Django 3.0.3 on 2020-03-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_base_view'),
        ('product', '0009_auto_20200314_1537'),
    ]

    operations = [
    ]
