# Generated by Django 3.0.3 on 2020-03-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_merge_20200315_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_view',
        ),
    ]
