# Generated by Django 3.0.3 on 2020-03-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200315_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='CategoryID',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Category ID'),
            preserve_default=False,
        ),
    ]
