# Generated by Django 3.0.3 on 2020-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('model', models.CharField(max_length=30)),
                ('review', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
