# Generated by Django 3.0.3 on 2020-03-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brand_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='BRDCategoryID',
            new_name='categoryID',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='BRDName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CName',
            new_name='name',
        ),
    ]
