# Generated by Django 3.0.3 on 2020-03-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200306_0459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
