# Generated by Django 3.0.3 on 2020-03-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200309_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.RemoveField(
            model_name='productpicture',
            name='whole_view',
        ),
        migrations.AddField(
            model_name='product',
            name='BID',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='product.Brand', verbose_name='Brand ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_items',
            field=models.IntegerField(default=True, verbose_name='Product Items in Stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpicture',
            name='front_view',
            field=models.ImageField(default=True, upload_to='', verbose_name='Product Front Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Product Model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(verbose_name='Product Comment'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='review',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Product Stars Review'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='inner_view',
            field=models.ImageField(upload_to='', verbose_name='Product Inner Image'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='side_view',
            field=models.ImageField(upload_to='', verbose_name='Product Side Image'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='top_view',
            field=models.ImageField(upload_to='', verbose_name='Product Top Image'),
        ),
    ]
